async (page) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const check = (value, message) => { if (!value) throw new Error(message); };
  const ready = () => page.getByText('Plan ready', { exact: true }).waitFor();
  const library = () => page.evaluate(() => JSON.parse(localStorage.getItem('cargo-twin-projects-v2')).projects);
  const projectName = page.getByRole('textbox', { name: 'Project name' });
  const openProject = async name => {
    await page.getByRole('button', { name: 'Projects', exact: true }).click();
    await page.getByRole('dialog').locator('.ct-project-list article').filter({ hasText: name }).getByRole('button', { name: 'Open' }).click();
    await ready();
  };
  await page.addInitScript(() => {
    if (window.top !== window) return;
    if (localStorage.getItem('cargo-twin-qa-clean-journey')) Object.keys(localStorage).filter(key => key.startsWith('cargo-twin-')).forEach(key => localStorage.removeItem(key));
  });
  await page.evaluate(() => localStorage.setItem('cargo-twin-qa-clean-journey', '1'));
  await page.reload(); await ready();
  await projectName.fill('QA Alpha');
  await projectName.press('Control+s');
  await page.getByRole('status').filter({ hasText: 'saved in your project library' }).waitFor();
  const alpha = (await library()).find(project => project.name === 'QA Alpha');
  check(alpha, 'Ctrl+S in an input must save the app project.');
  await page.getByRole('button', { name: 'New project', exact: true }).click(); await ready();
  await projectName.fill('QA Beta');
  await page.getByRole('tab', { name: 'Cargo', exact: true }).click();
  await page.getByRole('button', { name: 'Add cargo type' }).click();
  await page.locator('.ct-pack-button').click(); await ready();
  await page.getByRole('button', { name: 'Save project', exact: true }).click();
  const beta = (await library()).find(project => project.name === 'QA Beta');
  check(beta && beta.id !== alpha.id, 'A new project must have its own identity.');
  await openProject('QA Alpha'); await openProject('QA Beta');
  await page.getByRole('button', { name: 'Undo edit' }).click();
  check(await projectName.inputValue() === 'QA Alpha', 'Undo must restore the prior project document.');
  await projectName.fill('QA Alpha revised');
  await page.getByRole('button', { name: 'Save project', exact: true }).click();
  let saved = await library();
  check(saved.find(project => project.id === alpha.id)?.name === 'QA Alpha revised', 'Undo must restore the matching saved project ID.');
  check(saved.find(project => project.id === beta.id)?.name === 'QA Beta', 'Saving after undo must not overwrite another project.');
  await page.reload(); await ready();
  await page.getByRole('button', { name: 'Save project', exact: true }).click();
  saved = await library();
  check(saved.length === 2, 'Reload and Save must update the saved ID, without a duplicate.');
  await projectName.fill('');
  await page.getByRole('button', { name: 'Load sheet', exact: true }).first().click();
  await page.getByRole('status').filter({ hasText: 'Project name' }).waitFor();
  check(await page.getByRole('heading', { name: 'Plan your load.' }).isVisible(), 'Invalid report input must leave the app intact.');
  await page.getByRole('button', { name: 'Undo edit' }).click();
  await page.locator('.ct-plan-overview').getByRole('button', { name: 'Compare approaches', exact: true }).click();
  await page.locator('.ct-comparison-grid').waitFor();
  await page.locator('.ct-comparison-grid article').filter({ has: page.getByRole('heading', { name: 'Balanced', exact: true }) }).getByRole('button', { name: 'Use this plan' }).click();
  check(await page.getByRole('button', { name: 'Undo edit' }).isEnabled(), 'Applying an alternative plan must be undoable.');
  check(await page.getByRole('button', { name: 'Redo edit' }).isDisabled(), 'Applying an alternative must clear the old redo branch.');
  await page.getByRole('button', { name: 'Undo edit' }).click();
  await page.getByRole('button', { name: 'Redo edit' }).click(); await ready();
  await page.getByRole('button', { name: 'Load sheet', exact: true }).first().click();
  await page.getByRole('dialog').waitFor();
  const report = await page.frameLocator('iframe[title="Load sheet preview"]').locator('body').innerText();
  check(report.includes('40 / 40') && report.includes('551 kg') && report.includes('Planning limits'), 'Preview must show current packed metrics and planning scope.');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'Export files' }).click();
  const jsonDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: /Project JSON/ }).click();
  const json = await jsonDownload; await json.saveAs('output/playwright/qa-project.json');
  const csvDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: /Manifest CSV/ }).click();
  const csv = await csvDownload; await csv.saveAs('output/playwright/qa-manifest.csv');
  const planDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: /Placement CSV/ }).click();
  await (await planDownload).saveAs('output/playwright/qa-placements.csv');
  const htmlDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: /Printable load sheet/ }).click();
  await (await htmlDownload).saveAs('output/playwright/qa-load-sheet.html');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.locator('input[type=file]').first().setInputFiles('output/playwright/qa-project.json'); await ready();
  await page.locator('input[type=file]').nth(1).setInputFiles('output/playwright/qa-manifest.csv'); await ready();
  check(await projectName.inputValue() === 'QA Alpha revised', 'JSON and CSV reimports must preserve project contents.');
  await page.getByRole('tab', { name: 'Cargo', exact: true }).click();
  await page.getByRole('button', { name: /^Everyday cartons/ }).click();
  await page.getByRole('spinbutton', { name: 'Quantity', exact: true }).fill('17');
  await page.getByRole('tab', { name: 'Load insights' }).click();
  await page.getByText('Previous plan details. Build an updated plan for your current cargo and space.').waitFor();
  await page.getByRole('button', { name: 'Export files' }).click();
  check(await page.getByRole('button', { name: /Placement CSV/ }).isDisabled(), 'Stale calculated exports must be disabled.');
  await page.getByRole('button', { name: 'Close dialog' }).click();
  await page.getByRole('button', { name: 'Undo edit' }).click();
  await page.getByRole('button', { name: 'Redo edit' }).click();
  await page.locator('.ct-pack-button').click(); await ready();
  await page.getByRole('complementary', { name: 'Current plan metrics' }).waitFor();
  check((await page.locator('.ct-fit-summary > strong small').innerText()).trim() === '/ 41', 'Editing and repacking must refresh requested counts.');
  await page.addInitScript(() => {
    if (window.top !== window) return;
    if (localStorage.getItem('cargo-twin-qa-corrupt-on-boot')) {
      localStorage.removeItem('cargo-twin-qa-corrupt-on-boot');
      localStorage.setItem('cargo-twin-autosave-v2', '{damaged-recoverable-draft');
    }
  });
  await page.evaluate(() => localStorage.setItem('cargo-twin-qa-corrupt-on-boot', '1'));
  await page.reload(); await ready();
  await page.getByText('Your stored draft needs recovery.').waitFor();
  await page.waitForTimeout(800);
  check(await page.evaluate(() => localStorage.getItem('cargo-twin-autosave-v2')) === '{damaged-recoverable-draft', 'Startup must not replace corrupt recovery data.');
  await page.getByRole('button', { name: 'Use current draft' }).click();
  check(await page.evaluate(() => Object.keys(localStorage).some(key => key.startsWith('cargo-twin-autosave-v2-recovery-') && localStorage.getItem(key) === '{damaged-recoverable-draft')), 'Resuming autosave must preserve original recovery bytes.');
  check(errors.length === 0, 'Browser page errors: ' + errors.join('; '));
  return 'PASS: named projects; Ctrl+S; cross-project undo/save; reload identity; invalid report name; comparison undo/redo; report preview; four exports; JSON/CSV reimports; stale export gate; repacking; corrupt draft recovery. Zero page errors.';
}
